-- Note: create the database once before running this script:
-- CREATE DATABASE artconnect;

\c artconnect

DROP TABLE IF EXISTS reviews;
DROP TABLE IF EXISTS bookings;
DROP TABLE IF EXISTS member_favorite_disciplines;
DROP TABLE IF EXISTS exhibition_artworks;
DROP TABLE IF EXISTS artwork_tags_map;
DROP TABLE IF EXISTS artist_disciplines;
DROP TABLE IF EXISTS exhibitions;
DROP TABLE IF EXISTS workshops;
DROP TABLE IF EXISTS community_members;
DROP TABLE IF EXISTS artworks;
DROP TABLE IF EXISTS galleries;
DROP TABLE IF EXISTS artwork_tags;
DROP TABLE IF EXISTS disciplines;
DROP TABLE IF EXISTS artists;

CREATE TABLE artists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    bio TEXT,
    birth_year INT,
    contact_email VARCHAR(255),
    phone VARCHAR(50),
    city VARCHAR(120),
    website VARCHAR(255),
    social_media VARCHAR(255),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_artist_name UNIQUE (name),
    CONSTRAINT uq_artist_contact_email UNIQUE (contact_email)
);

CREATE TABLE disciplines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    CONSTRAINT uq_discipline_name UNIQUE (name)
);

CREATE TABLE artist_disciplines (
    artist_id BIGINT NOT NULL,
    discipline_id BIGINT NOT NULL,
    PRIMARY KEY (artist_id, discipline_id),
    CONSTRAINT fk_artist_disciplines_artist
        FOREIGN KEY (artist_id) REFERENCES artists(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_artist_disciplines_discipline
        FOREIGN KEY (discipline_id) REFERENCES disciplines(id)
        ON DELETE CASCADE
);

CREATE TABLE artwork_tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    CONSTRAINT uq_artwork_tag_name UNIQUE (name)
);

CREATE TABLE artworks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(180) NOT NULL,
    creation_year INT,
    type VARCHAR(100),
    medium VARCHAR(120),
    dimensions VARCHAR(120),
    description TEXT,
    price DECIMAL(12, 2) NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL DEFAULT 'FOR_SALE',
    artist_id BIGINT NOT NULL,
    CONSTRAINT uq_artwork_title_artist UNIQUE (title, artist_id),
    CONSTRAINT chk_artwork_price CHECK (price >= 0),
    CONSTRAINT chk_artwork_status CHECK (status IN ('FOR_SALE', 'SOLD', 'EXHIBITED')),
    CONSTRAINT fk_artworks_artist
        FOREIGN KEY (artist_id) REFERENCES artists(id)
        ON DELETE RESTRICT
);

CREATE TABLE artwork_tags_map (
    artwork_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL,
    PRIMARY KEY (artwork_id, tag_id),
    CONSTRAINT fk_artwork_tags_map_artwork
        FOREIGN KEY (artwork_id) REFERENCES artworks(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_artwork_tags_map_tag
        FOREIGN KEY (tag_id) REFERENCES artwork_tags(id)
        ON DELETE CASCADE
);

CREATE TABLE galleries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(180) NOT NULL,
    address VARCHAR(255),
    owner_name VARCHAR(150),
    opening_hours VARCHAR(120),
    contact_phone VARCHAR(50),
    rating DECIMAL(3, 2) NOT NULL DEFAULT 0,
    website VARCHAR(255),
    CONSTRAINT uq_gallery_name UNIQUE (name),
    CONSTRAINT chk_gallery_rating CHECK (rating >= 0 AND rating <= 5)
);

CREATE TABLE exhibitions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(180) NOT NULL,
    start_date DATE,
    end_date DATE,
    description TEXT,
    gallery_id BIGINT,
    curator_name VARCHAR(150),
    theme VARCHAR(120),
    CONSTRAINT uq_exhibition_title UNIQUE (title),
    CONSTRAINT chk_exhibition_dates CHECK (end_date IS NULL OR start_date IS NULL OR end_date >= start_date),
    CONSTRAINT fk_exhibitions_gallery
        FOREIGN KEY (gallery_id) REFERENCES galleries(id)
        ON DELETE SET NULL
);

CREATE TABLE exhibition_artworks (
    exhibition_id BIGINT NOT NULL,
    artwork_id BIGINT NOT NULL,
    PRIMARY KEY (exhibition_id, artwork_id),
    CONSTRAINT fk_exhibition_artworks_exhibition
        FOREIGN KEY (exhibition_id) REFERENCES exhibitions(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_exhibition_artworks_artwork
        FOREIGN KEY (artwork_id) REFERENCES artworks(id)
        ON DELETE CASCADE
);

CREATE TABLE community_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    email VARCHAR(255) NOT NULL,
    birth_year INT,
    phone VARCHAR(50),
    city VARCHAR(120),
    membership_type VARCHAR(20),
    CONSTRAINT uq_community_member_email UNIQUE (email),
    CONSTRAINT chk_community_membership_type CHECK (membership_type IN ('free', 'premium') OR membership_type IS NULL)
);

CREATE TABLE member_favorite_disciplines (
    member_id BIGINT NOT NULL,
    discipline_id BIGINT NOT NULL,
    PRIMARY KEY (member_id, discipline_id),
    CONSTRAINT fk_member_favorite_disciplines_member
        FOREIGN KEY (member_id) REFERENCES community_members(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_member_favorite_disciplines_discipline
        FOREIGN KEY (discipline_id) REFERENCES disciplines(id)
        ON DELETE CASCADE
);

CREATE TABLE workshops (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(180) NOT NULL,
    workshop_date TIMESTAMP NOT NULL,
    duration_minutes INT,
    max_participants INT,
    price DECIMAL(12, 2) NOT NULL DEFAULT 0,
    instructor_id BIGINT,
    location VARCHAR(180),
    description TEXT,
    level VARCHAR(20),
    CONSTRAINT uq_workshop_title_date UNIQUE (title, workshop_date),
    CONSTRAINT chk_workshop_duration CHECK (duration_minutes IS NULL OR duration_minutes > 0),
    CONSTRAINT chk_workshop_max_participants CHECK (max_participants IS NULL OR max_participants > 0),
    CONSTRAINT chk_workshop_price CHECK (price >= 0),
    CONSTRAINT chk_workshop_level CHECK (level IN ('beginner', 'intermediate', 'advanced') OR level IS NULL),
    CONSTRAINT fk_workshops_instructor
        FOREIGN KEY (instructor_id) REFERENCES artists(id)
        ON DELETE SET NULL
);

CREATE TABLE bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workshop_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    booking_date TIMESTAMP NOT NULL,
    payment_status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    CONSTRAINT uq_booking_workshop_member UNIQUE (workshop_id, member_id),
    CONSTRAINT chk_booking_payment_status CHECK (payment_status IN ('PENDING', 'PAID', 'CANCELLED')),
    CONSTRAINT fk_bookings_workshop
        FOREIGN KEY (workshop_id) REFERENCES workshops(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_bookings_member
        FOREIGN KEY (member_id) REFERENCES community_members(id)
        ON DELETE CASCADE
);

CREATE TABLE reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reviewer_member_id BIGINT NOT NULL,
    artwork_id BIGINT NOT NULL,
    rating INT NOT NULL,
    comment TEXT,
    review_date DATE NOT NULL,
    CONSTRAINT uq_review_reviewer_artwork UNIQUE (reviewer_member_id, artwork_id),
    CONSTRAINT chk_review_rating CHECK (rating BETWEEN 1 AND 5),
    CONSTRAINT fk_reviews_reviewer
        FOREIGN KEY (reviewer_member_id) REFERENCES community_members(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_reviews_artwork
        FOREIGN KEY (artwork_id) REFERENCES artworks(id)
        ON DELETE CASCADE
);

CREATE INDEX idx_artists_city ON artists(city);
CREATE INDEX idx_artworks_artist_id ON artworks(artist_id);
CREATE INDEX idx_exhibitions_gallery_id ON exhibitions(gallery_id);
CREATE INDEX idx_workshops_instructor_id ON workshops(instructor_id);
CREATE INDEX idx_bookings_workshop_id ON bookings(workshop_id);
CREATE INDEX idx_bookings_member_id ON bookings(member_id);
CREATE INDEX idx_reviews_artwork_id ON reviews(artwork_id);
CREATE INDEX idx_reviews_reviewer_member_id ON reviews(reviewer_member_id);

