-- Note: create the database once before running this script:
-- CREATE DATABASE artconnect;

\c artconnect

-- Cleanup advanced objects first so table drops remain rerunnable.
DROP VIEW IF EXISTS vw_member_activity_summary;
DROP VIEW IF EXISTS vw_workshop_capacity;
DROP VIEW IF EXISTS vw_public_artist_profiles;

DROP FUNCTION IF EXISTS fn_workshops_audit();
DROP FUNCTION IF EXISTS fn_sync_artwork_exhibited_status();
DROP FUNCTION IF EXISTS fn_validate_booking_capacity_and_date();
DROP FUNCTION IF EXISTS fn_normalize_member_data();
DROP FUNCTION IF EXISTS fn_artist_average_rating(BIGINT);
DROP FUNCTION IF EXISTS fn_workshop_available_seats(BIGINT);
DROP FUNCTION IF EXISTS fn_workshop_participant_count(BIGINT);

DROP PROCEDURE IF EXISTS sp_register_member_for_workshops(BIGINT, BIGINT[]);
DROP TABLE IF EXISTS workshop_audit;

DROP TABLE IF EXISTS reviews;
DROP TABLE IF EXISTS bookings;
DROP TABLE IF EXISTS member_favorite_disciplines;
DROP TABLE IF EXISTS exhibition_artworks;
DROP TABLE IF EXISTS artwork_tags_map;
DROP TABLE IF EXISTS artist_disciplines;
DROP TABLE IF EXISTS exhibitions;
DROP TABLE IF EXISTS workshops;
DROP TABLE IF EXISTS community_members;
DROP TABLE IF EXISTS artworks;
DROP TABLE IF EXISTS galleries;
DROP TABLE IF EXISTS artwork_tags;
DROP TABLE IF EXISTS disciplines;
DROP TABLE IF EXISTS artists;

CREATE TABLE artists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    bio TEXT,
    birth_year INT,
    contact_email VARCHAR(255),
    phone VARCHAR(50),
    city VARCHAR(120),
    website VARCHAR(255),
    social_media VARCHAR(255),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_artist_name UNIQUE (name),
    CONSTRAINT uq_artist_contact_email UNIQUE (contact_email)
);

CREATE TABLE disciplines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    CONSTRAINT uq_discipline_name UNIQUE (name)
);

CREATE TABLE artist_disciplines (
    artist_id BIGINT NOT NULL,
    discipline_id BIGINT NOT NULL,
    PRIMARY KEY (artist_id, discipline_id),
    CONSTRAINT fk_artist_disciplines_artist
        FOREIGN KEY (artist_id) REFERENCES artists(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_artist_disciplines_discipline
        FOREIGN KEY (discipline_id) REFERENCES disciplines(id)
        ON DELETE CASCADE
);

CREATE TABLE artwork_tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    CONSTRAINT uq_artwork_tag_name UNIQUE (name)
);

CREATE TABLE artworks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(180) NOT NULL,
    creation_year INT,
    type VARCHAR(100),
    medium VARCHAR(120),
    dimensions VARCHAR(120),
    description TEXT,
    price DECIMAL(12, 2) NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL DEFAULT 'FOR_SALE',
    artist_id BIGINT NOT NULL,
    CONSTRAINT uq_artwork_title_artist UNIQUE (title, artist_id),
    CONSTRAINT chk_artwork_price CHECK (price >= 0),
    CONSTRAINT chk_artwork_status CHECK (status IN ('FOR_SALE', 'SOLD', 'EXHIBITED')),
    CONSTRAINT fk_artworks_artist
        FOREIGN KEY (artist_id) REFERENCES artists(id)
        ON DELETE RESTRICT
);

CREATE TABLE artwork_tags_map (
    artwork_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL,
    PRIMARY KEY (artwork_id, tag_id),
    CONSTRAINT fk_artwork_tags_map_artwork
        FOREIGN KEY (artwork_id) REFERENCES artworks(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_artwork_tags_map_tag
        FOREIGN KEY (tag_id) REFERENCES artwork_tags(id)
        ON DELETE CASCADE
);

CREATE TABLE galleries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(180) NOT NULL,
    address VARCHAR(255),
    owner_name VARCHAR(150),
    opening_hours VARCHAR(120),
    contact_phone VARCHAR(50),
    rating DECIMAL(3, 2) NOT NULL DEFAULT 0,
    website VARCHAR(255),
    CONSTRAINT uq_gallery_name UNIQUE (name),
    CONSTRAINT chk_gallery_rating CHECK (rating >= 0 AND rating <= 5)
);

CREATE TABLE exhibitions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(180) NOT NULL,
    start_date DATE,
    end_date DATE,
    description TEXT,
    gallery_id BIGINT,
    curator_name VARCHAR(150),
    theme VARCHAR(120),
    CONSTRAINT uq_exhibition_title UNIQUE (title),
    CONSTRAINT chk_exhibition_dates CHECK (end_date IS NULL OR start_date IS NULL OR end_date >= start_date),
    CONSTRAINT fk_exhibitions_gallery
        FOREIGN KEY (gallery_id) REFERENCES galleries(id)
        ON DELETE SET NULL
);

CREATE TABLE exhibition_artworks (
    exhibition_id BIGINT NOT NULL,
    artwork_id BIGINT NOT NULL,
    PRIMARY KEY (exhibition_id, artwork_id),
    CONSTRAINT fk_exhibition_artworks_exhibition
        FOREIGN KEY (exhibition_id) REFERENCES exhibitions(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_exhibition_artworks_artwork
        FOREIGN KEY (artwork_id) REFERENCES artworks(id)
        ON DELETE CASCADE
);

CREATE TABLE community_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    email VARCHAR(255) NOT NULL,
    birth_year INT,
    phone VARCHAR(50),
    city VARCHAR(120),
    membership_type VARCHAR(20),
    CONSTRAINT uq_community_member_email UNIQUE (email),
    CONSTRAINT chk_community_membership_type CHECK (membership_type IN ('free', 'premium') OR membership_type IS NULL)
);

CREATE TABLE member_favorite_disciplines (
    member_id BIGINT NOT NULL,
    discipline_id BIGINT NOT NULL,
    PRIMARY KEY (member_id, discipline_id),
    CONSTRAINT fk_member_favorite_disciplines_member
        FOREIGN KEY (member_id) REFERENCES community_members(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_member_favorite_disciplines_discipline
        FOREIGN KEY (discipline_id) REFERENCES disciplines(id)
        ON DELETE CASCADE
);

CREATE TABLE workshops (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(180) NOT NULL,
    workshop_date TIMESTAMP NOT NULL,
    duration_minutes INT,
    max_participants INT,
    price DECIMAL(12, 2) NOT NULL DEFAULT 0,
    instructor_id BIGINT,
    location VARCHAR(180),
    description TEXT,
    level VARCHAR(20),
    CONSTRAINT uq_workshop_title_date UNIQUE (title, workshop_date),
    CONSTRAINT chk_workshop_duration CHECK (duration_minutes IS NULL OR duration_minutes > 0),
    CONSTRAINT chk_workshop_max_participants CHECK (max_participants IS NULL OR max_participants > 0),
    CONSTRAINT chk_workshop_price CHECK (price >= 0),
    CONSTRAINT chk_workshop_level CHECK (level IN ('beginner', 'intermediate', 'advanced') OR level IS NULL),
    CONSTRAINT fk_workshops_instructor
        FOREIGN KEY (instructor_id) REFERENCES artists(id)
        ON DELETE SET NULL
);

CREATE TABLE bookings (
    workshop_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    booking_date TIMESTAMP NOT NULL,
    payment_status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    CONSTRAINT pk_workshop_member PRIMARY KEY (workshop_id, member_id),
    CONSTRAINT chk_booking_payment_status CHECK (payment_status IN ('PENDING', 'PAID', 'CANCELLED')),
    CONSTRAINT fk_bookings_workshop
        FOREIGN KEY (workshop_id) REFERENCES workshops(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_bookings_member
        FOREIGN KEY (member_id) REFERENCES community_members(id)
        ON DELETE CASCADE
);

CREATE TABLE reviews (
    reviewer_member_id BIGINT NOT NULL,
    artwork_id BIGINT NOT NULL,
    rating INT NOT NULL,
    comment TEXT,
    review_date DATE NOT NULL,
    CONSTRAINT pk_artwork_reviewer_member PRIMARY KEY (reviewer_member_id, artwork_id),
    CONSTRAINT chk_review_rating CHECK (rating BETWEEN 1 AND 5),
    CONSTRAINT fk_reviews_reviewer
        FOREIGN KEY (reviewer_member_id) REFERENCES community_members(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_reviews_artwork
        FOREIGN KEY (artwork_id) REFERENCES artworks(id)
        ON DELETE CASCADE
);

CREATE INDEX idx_artists_city ON artists(city);
CREATE INDEX idx_artworks_artist_id ON artworks(artist_id);
CREATE INDEX idx_exhibitions_gallery_id ON exhibitions(gallery_id);
CREATE INDEX idx_workshops_instructor_id ON workshops(instructor_id);
CREATE INDEX idx_bookings_member_id ON bookings(member_id);
CREATE INDEX idx_reviews_artwork_id ON reviews(artwork_id);

-- Extra composite indexes for common filtering/sorting patterns in dashboards.
CREATE INDEX idx_artworks_status_price ON artworks(status, price);
COMMENT ON INDEX idx_artworks_status_price IS
    'Speeds status-based catalog filtering and secondary sorting by price.';

CREATE INDEX idx_workshops_date_level ON workshops(workshop_date, level);
COMMENT ON INDEX idx_workshops_date_level IS
    'Speeds upcoming-workshop searches filtered by level and ordered by date.';

CREATE INDEX idx_bookings_workshop_payment ON bookings(workshop_id, payment_status);
COMMENT ON INDEX idx_bookings_workshop_payment IS
    'Speeds seat calculations and payment-status reporting per workshop.';

-- ===== Views =====
-- 1) Security view: expose artist profile without private direct contacts.
CREATE VIEW vw_public_artist_profiles AS
SELECT
    a.id,
    a.name,
    a.bio,
    a.birth_year,
    a.city,
    a.website,
    a.social_media,
    a.is_active
FROM artists a;

-- 2) Simplification view: one-row workshop capacity snapshot.
CREATE VIEW vw_workshop_capacity AS
SELECT
    w.id AS workshop_id,
    w.title,
    w.workshop_date,
    w.level,
    w.max_participants,
    COUNT(*) FILTER (WHERE b.payment_status <> 'CANCELLED')::INT AS confirmed_participants,
    CASE
        WHEN w.max_participants IS NULL THEN NULL
        ELSE (w.max_participants - COUNT(*) FILTER (WHERE b.payment_status <> 'CANCELLED'))::INT
    END AS available_seats
FROM workshops w
LEFT JOIN bookings b ON b.workshop_id = w.id
GROUP BY w.id, w.title, w.workshop_date, w.level, w.max_participants;

-- 3) Analytics view: aggregate member engagement for quick community reporting.
CREATE VIEW vw_member_activity_summary AS
SELECT
    m.id AS member_id,
    m.name,
    m.email,
    m.membership_type,
    COUNT(DISTINCT (b.workshop_id, b.member_id)) AS bookings_count,
    COUNT(DISTINCT r.artwork_id) AS reviews_count,
    MAX(b.booking_date) AS last_booking_at,
    MAX(r.review_date) AS last_review_on
FROM community_members m
LEFT JOIN bookings b ON b.member_id = m.id
LEFT JOIN reviews r ON r.reviewer_member_id = m.id
GROUP BY m.id, m.name, m.email, m.membership_type;

-- Access rights: expose read-only reporting through views.
GRANT SELECT ON vw_public_artist_profiles TO PUBLIC;
GRANT SELECT ON vw_workshop_capacity TO PUBLIC;
GRANT SELECT ON vw_member_activity_summary TO PUBLIC;

-- ===== Trigger support tables and functions =====
CREATE TABLE workshop_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workshop_id BIGINT,
    operation VARCHAR(10) NOT NULL,
    changed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    changed_by TEXT NOT NULL DEFAULT CURRENT_USER,
    old_data JSONB,
    new_data JSONB
);

-- Normalizes email + membership type to keep input canonical for lookups.
CREATE OR REPLACE FUNCTION fn_normalize_member_data()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.email := LOWER(TRIM(NEW.email));

    IF NEW.membership_type IS NOT NULL THEN
        NEW.membership_type := LOWER(TRIM(NEW.membership_type));
    END IF;

    RETURN NEW;
END;
$$;

-- Ensures booking date consistency and protects workshop capacity.
CREATE OR REPLACE FUNCTION fn_validate_booking_capacity_and_date()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_workshop_date TIMESTAMP;
    v_max_participants INT;
    v_active_bookings INT;
BEGIN
    SELECT workshop_date, max_participants
    INTO v_workshop_date, v_max_participants
    FROM workshops
    WHERE id = NEW.workshop_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Workshop % not found for booking.', NEW.workshop_id;
    END IF;

    IF NEW.booking_date IS NULL THEN
        NEW.booking_date := CURRENT_TIMESTAMP;
    END IF;

    IF NEW.booking_date > v_workshop_date THEN
        RAISE EXCEPTION 'Booking date (%) cannot be after workshop date (%).', NEW.booking_date, v_workshop_date;
    END IF;

    IF COALESCE(NEW.payment_status, 'PENDING') <> 'CANCELLED' AND v_max_participants IS NOT NULL THEN
        SELECT COUNT(*)
        INTO v_active_bookings
        FROM bookings b
        WHERE b.workshop_id = NEW.workshop_id
          AND b.payment_status <> 'CANCELLED'
          AND (
              TG_OP = 'INSERT'
              OR (b.workshop_id, b.member_id) <> (OLD.workshop_id, OLD.member_id)
          );

        IF v_active_bookings >= v_max_participants THEN
            RAISE EXCEPTION 'Workshop % is full (% seats).', NEW.workshop_id, v_max_participants;
        END IF;
    END IF;

    RETURN NEW;
END;
$$;

-- Keeps artwork status aligned with exhibition participation.
CREATE OR REPLACE FUNCTION fn_sync_artwork_exhibited_status()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_artwork_id BIGINT;
    v_links INT;
BEGIN
    v_artwork_id := COALESCE(NEW.artwork_id, OLD.artwork_id);

    IF TG_OP = 'INSERT' THEN
        UPDATE artworks
        SET status = 'EXHIBITED'
        WHERE id = NEW.artwork_id
          AND status <> 'SOLD';
        RETURN NEW;
    END IF;

    SELECT COUNT(*) INTO v_links
    FROM exhibition_artworks
    WHERE artwork_id = v_artwork_id;

    IF v_links = 0 THEN
        UPDATE artworks
        SET status = 'FOR_SALE'
        WHERE id = v_artwork_id
          AND status = 'EXHIBITED';
    END IF;

    RETURN COALESCE(NEW, OLD);
END;
$$;

-- Audits workshop lifecycle changes for accountability.
CREATE OR REPLACE FUNCTION fn_workshops_audit()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    INSERT INTO workshop_audit (workshop_id, operation, old_data, new_data)
    VALUES (
        COALESCE(NEW.id, OLD.id),
        TG_OP,
        CASE WHEN TG_OP IN ('UPDATE', 'DELETE') THEN TO_JSONB(OLD) ELSE NULL END,
        CASE WHEN TG_OP IN ('INSERT', 'UPDATE') THEN TO_JSONB(NEW) ELSE NULL END
    );

    RETURN COALESCE(NEW, OLD);
END;
$$;

-- ===== Triggers =====
CREATE TRIGGER trg_community_members_normalize
BEFORE INSERT OR UPDATE ON community_members
FOR EACH ROW
EXECUTE FUNCTION fn_normalize_member_data();

CREATE TRIGGER trg_bookings_capacity_guard
BEFORE INSERT OR UPDATE OF workshop_id, booking_date, payment_status ON bookings
FOR EACH ROW
EXECUTE FUNCTION fn_validate_booking_capacity_and_date();

CREATE TRIGGER trg_exhibition_artwork_status_sync
AFTER INSERT OR DELETE ON exhibition_artworks
FOR EACH ROW
EXECUTE FUNCTION fn_sync_artwork_exhibited_status();

CREATE TRIGGER trg_workshops_audit
AFTER INSERT OR UPDATE OR DELETE ON workshops
FOR EACH ROW
EXECUTE FUNCTION fn_workshops_audit();

-- ===== Stored programs (functions/procedure) =====
-- Returns active (non-cancelled) participant count for one workshop.
CREATE OR REPLACE FUNCTION fn_workshop_participant_count(p_workshop_id BIGINT)
RETURNS INT
LANGUAGE SQL
AS $$
    SELECT COUNT(*)::INT
    FROM bookings
    WHERE workshop_id = p_workshop_id
      AND payment_status <> 'CANCELLED';
$$;

-- Returns available seats; NULL means unlimited workshop capacity.
CREATE OR REPLACE FUNCTION fn_workshop_available_seats(p_workshop_id BIGINT)
RETURNS INT
LANGUAGE plpgsql
AS $$
DECLARE
    v_max INT;
BEGIN
    SELECT max_participants INTO v_max
    FROM workshops
    WHERE id = p_workshop_id;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Workshop % does not exist.', p_workshop_id;
    END IF;

    IF v_max IS NULL THEN
        RETURN NULL;
    END IF;

    RETURN v_max - fn_workshop_participant_count(p_workshop_id);
END;
$$;

-- Returns average rating received by an artist across their artworks.
CREATE OR REPLACE FUNCTION fn_artist_average_rating(p_artist_id BIGINT)
RETURNS DECIMAL(4, 2)
LANGUAGE SQL
AS $$
    SELECT ROUND(AVG(r.rating)::NUMERIC, 2)::DECIMAL(4, 2)
    FROM reviews r
    JOIN artworks a ON a.id = r.artwork_id
    WHERE a.artist_id = p_artist_id;
$$;

-- Atomic operation: register one member to multiple workshops in one call.
CREATE OR REPLACE PROCEDURE sp_register_member_for_workshops(
    p_member_id BIGINT,
    p_workshop_ids BIGINT[]
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_workshop_id BIGINT;
BEGIN
    IF p_workshop_ids IS NULL OR ARRAY_LENGTH(p_workshop_ids, 1) IS NULL THEN
        RAISE EXCEPTION 'workshop_ids cannot be empty.';
    END IF;

    PERFORM 1 FROM community_members WHERE id = p_member_id;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Member % not found.', p_member_id;
    END IF;

    FOREACH v_workshop_id IN ARRAY p_workshop_ids LOOP
        INSERT INTO bookings (workshop_id, member_id, booking_date, payment_status)
        VALUES (v_workshop_id, p_member_id, CURRENT_TIMESTAMP, 'PENDING');
    END LOOP;
END;
$$;

-- ===== Example complex transaction scenario =====
-- Objective: register a member to multiple workshops atomically and audit outcome.
-- If any workshop is full (trigger) or duplicate booking exists (unique key),
-- the whole transaction is rolled back.
--
-- BEGIN;
-- CALL sp_register_member_for_workshops(1, ARRAY[1, 2, 3]);
-- INSERT INTO reviews (reviewer_member_id, artwork_id, rating, comment, review_date)
-- VALUES (1, 2, 5, 'Booked workshops and reviewed an exhibition piece.', CURRENT_DATE)
-- ON CONFLICT (reviewer_member_id, artwork_id) DO NOTHING;
-- COMMIT;

